---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Primary:
    - CasaOS:
        href: http://172.31.143.34/#/
        description: Home Server
